server:
  port: 8081
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: iovu
    password: iovu
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#  social login : google kakao naver 이런식으로
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: #입력해야됨
#            client-secret: #입력해야됨
#          scope:
#            - email
#            - profile
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iovu.iovuback.domain

#pdf
pdf:
  font:
    path: classpath:fonts/NanumGothic.ttf